language: python
env:
    # putting this ahead of the `python` directive
    #   means we start all lints before any tests
    - TOXENV=lint
    - TOXENV=python
python:
    # in order of most-valuable tests first
    - "3.6"
    - "2.6"
    - pypy
    - "2.7"
    - "3.5"

addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python2.7-dev

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true
    # really only need to run lint twice
    exclude:
        - python: "2.6"
          env: TOXENV=lint
        - python: pypy
          env: TOXENV=lint
        - python: '3.5'
          env: TOXENV=lint

install: ./venv_update.py venv= $VIRTUAL_ENV install= -r CI/requirements.txt
script:
    - . CI/env
    - tox


# sudo:false gives us the new, faster cluster and enables caches for public repos
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
