language: python

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true
    # In order of most-valuable tests first
    include:
        - env: TOXENV=lint
          python: 3.6
        - env: TOXENV=lint
          python: 2.7

        - env: TOXENV=py38
          python: 3.8
        - env: TOXENV=py37
          python: 3.7
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=pypy
          python: pypy
        - env: TOXENV=py27
          python: 2.7
        - env: TOXENV=latest-pip
          python: 3.6

    allow_failures:
        # See #203
        - env: TOXENV=latest-pip
          python: 3.6

install: ./venv_update.py venv= $VIRTUAL_ENV install= -r CI/requirements.txt
script: tox

cache:
    directories:
        - $HOME/.pip
        - $HOME/.cache/pre-commit
