language: python
dist: trusty
env:
    # putting this ahead of the `python` directive
    #   means we start all lints before any tests
    - TOXENV=lint
    - TOXENV=python
python:
    - pypy

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true

install: ./venv_update.py venv= $VIRTUAL_ENV install= -r CI/requirements.txt
script:
    - . CI/env
    - tox


# sudo:required has pypy available on Trusty and also enables caches
# https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone
sudo: required
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
